export const START_GAME = "START_GAME"
export const RESUME_GAME = "RESUME_GAME"
export const GET_CHARACTER_READY_STATES = "GET_CHARACTER_READY_STATES"
export const ADD_TO_GAME = "ADD_TO_GAME"

export const PLACE_AGENT = "PLACE_AGENT"
export const USE_CARD = "USE_CARD"
export const DISCARD_CARD = "DISCARD_CARD"
export const TRASH_CARD = "TRASH_CARD"
export const ACQUIRE_CARD = "ACQUIRE_CARD"

export const CARD_USED = "CARD_USED"
export const UPDATE_PLAYER = "UPDATE_PLAYER"
export const UPDATE_LOCATION = "UPDATE_LOCATION"